"""chat logs traceability columns

Revision ID: 0d7214643b38
Revises: 8d9e0f1a2b3c
Create Date: 2026-08-30 14:00:54.027442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7214643b38'
down_revision: Union[str, None] = '8d9e0f1a2b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('model', sa.String(length=64), nullable=True))
    op.add_column('chat_logs', sa.Column('prompt_version', sa.String(length=16), nullable=True))
    op.add_column('chat_logs', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('chat_logs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('chat_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_logs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_logs_tenant_id'), 'chat_logs', ['tenant_id'], unique=False)

    # 存量回填：ORM 的 default 只作用于新插入的行，历史行会是 NULL，
    # 读出后 `log.model` 为 None，序列化与前端展示都会炸。这里统一兜底成零值。
    op.execute("UPDATE chat_logs SET model = '' WHERE model IS NULL")
    op.execute("UPDATE chat_logs SET prompt_version = '' WHERE prompt_version IS NULL")
    op.execute("UPDATE chat_logs SET status = 'ok' WHERE status IS NULL OR status = ''")
    op.execute("UPDATE chat_logs SET error = '' WHERE error IS NULL")
    op.execute("UPDATE chat_logs SET prompt_tokens = 0 WHERE prompt_tokens IS NULL")
    op.execute("UPDATE chat_logs SET completion_tokens = 0 WHERE completion_tokens IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_logs_tenant_id'), table_name='chat_logs')
    op.drop_column('chat_logs', 'completion_tokens')
    op.drop_column('chat_logs', 'prompt_tokens')
    op.drop_column('chat_logs', 'error')
    op.drop_column('chat_logs', 'status')
    op.drop_column('chat_logs', 'tenant_id')
    op.drop_column('chat_logs', 'prompt_version')
    op.drop_column('chat_logs', 'model')
    # ### end Alembic commands ###
