"""add_feedback_table：患者反馈表（反馈驱动自我优化闭环的输入）。

注意：``comment`` 列在 ORM 里是 ``EncryptedText``（应用层透明加密），
但**迁移中必须写底层物理类型 ``sa.Text()``** —— TypeDecorator 是应用层关注点，
schema 层面就是 TEXT。autogenerate 会把它渲染成 ``src.phi.EncryptedText()``
且不会自动加 import，直接跑会 NameError，故此处手工改回 ``sa.Text()``。

反馈闭环：``src/feedback.py`` 聚合差评 → 生成知识更新**提案** →
走 HITL 审批门（approvals.action='knowledge_update'）→ 批准后写入知识库。
医疗场景下严禁无人监督的自我改写，故「提案」与「落地」是分开的两步。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adb79c60a35'
down_revision: Union[str, None] = '9c4f2e8a71d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.String(length=8), nullable=False),
    # 物理类型 TEXT：加密由应用层 EncryptedText 装饰器负责（见 src/phi.py）
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('proposed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_thread_id'), 'feedback', ['thread_id'], unique=False)
    op.create_index(op.f('ix_feedback_trace_id'), 'feedback', ['trace_id'], unique=False)
    op.create_index(op.f('ix_feedback_username'), 'feedback', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_username'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_trace_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_thread_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
