"""add rollout configs

Revision ID: 76e2eddf3450
Revises: 2adb79c60a35
Create Date: 2026-08-30 05:18:32.975364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e2eddf3450'
down_revision: Union[str, None] = '2adb79c60a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollout_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_value', sa.String(length=64), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature', 'scope', 'scope_value', name='uq_rollout_feature_scope')
    )
    op.create_index(op.f('ix_rollout_configs_feature'), 'rollout_configs', ['feature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rollout_configs_feature'), table_name='rollout_configs')
    op.drop_table('rollout_configs')
    # ### end Alembic commands ###
